# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/f8aea2b6-fa06-4b7b-882b-aaa44a01c094";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/f8aea2b6-fa06-4b7b-882b-aaa44a01c094";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/f8aea2b6-fa06-4b7b-882b-aaa44a01c094";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/home/k3s-user/data" =
    {
      device = "/dev/disk/by-uuid/f8aea2b6-fa06-4b7b-882b-aaa44a01c094";
      fsType = "btrfs";
      options = [ "subvol=k3s-data" ];
    };

  fileSystems."/home/k3s-user/media" =
    {
      device = "/dev/disk/by-uuid/3aeb9e35-8858-41a6-95cc-2d36d9fb16e0";
      fsType = "btrfs";
      # This should really have used subvolumes...
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/F668-779D";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/c79e64f2-e629-4967-a96a-d825de548294"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.cni0.useDHCP = lib.mkDefault true;
  # networking.interfaces.flannel.1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth105cc019.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8340538c.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethabb4d8cc.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethd9ce4f87.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe5135833.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
